import { useEffect, useState } from "react";
import { useIsMounted } from "usehooks-ts";
import { Circuit, CircuitCodeStatus, CircuitName, circuits } from "~~/utils/noir/circuit";

/**
 * Gets the matching circuit info from the circuits file generated by `yarn deploy`
 * @param circuitName - name of deployed circuit
 */
export const useCircuitAbi = <TCircuitName extends CircuitName>(circuitName: TCircuitName) => {
  const isMounted = useIsMounted();
  const abi = circuits?.[circuitName].abi as Circuit<TCircuitName>["abi"];

  const [status, setStatus] = useState<CircuitCodeStatus>(CircuitCodeStatus.NOT_FOUND);

  useEffect(() => {
    const checkCircuitDeployment = async () => {
      if (!abi) {
        setStatus(CircuitCodeStatus.NOT_FOUND);
        return;
      }
      if (!isMounted()) {
        return;
      }
      setStatus(CircuitCodeStatus.FOUND);
    };

    checkCircuitDeployment();
  }, [isMounted, circuitName, abi]);

  return {
    abi: status === CircuitCodeStatus.FOUND ? abi : null,
  };
};
